services:
  postgres:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ams
      POSTGRES_PASSWORD: ams
      POSTGRES_DB: amscubing
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ams -d amscubing"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
